//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parkPullDBEntities2 : DbContext
    {
        public parkPullDBEntities2()
            : base("name=parkPullDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<daysAweekForOffer> daysAweekForOffers { get; set; }
        public virtual DbSet<daysAweekForRequest> daysAweekForRequests { get; set; }
        public virtual DbSet<Extension> Extensions { get; set; }
        public virtual DbSet<Opinion> Opinions { get; set; }
        public virtual DbSet<parkingRentalRequest> parkingRentalRequests { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<RentalOffersForParking> RentalOffersForParkings { get; set; }
        public virtual DbSet<rentedParking> rentedParkings { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
