//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parking()
        {
            this.RentalOffersForParkings = new HashSet<RentalOffersForParking>();
            this.Extensions = new HashSet<Extension>();
        }
    
        public int parkingCode { get; set; }
        public int userCode { get; set; }
        public Nullable<double> parkWidth { get; set; }
        public Nullable<double> parkLength { get; set; }
        public Nullable<double> parkHeight { get; set; }
        public Nullable<double> parkWeight { get; set; }
        public Nullable<double> price { get; set; }
        public string adress { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalOffersForParking> RentalOffersForParkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extension> Extensions { get; set; }
    }
}
