//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkingRentalRequests__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parkingRentalRequests__()
        {
            this.daysAweekForRequest = new HashSet<daysAweekForRequest>();
            this.rentedParkings = new HashSet<rentedParkings>();
            this.Extensions = new HashSet<Extensions>();
        }
    
        public int requestCode { get; set; }
        public int carCode { get; set; }
        public System.DateTime startDateForRequest { get; set; }
        public Nullable<System.DateTime> endDateForRequest { get; set; }
        public System.TimeSpan startHourForRequest { get; set; }
        public Nullable<System.TimeSpan> endHourForRequest { get; set; }
        public string requestAdress { get; set; }
    
        public virtual Cars Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daysAweekForRequest> daysAweekForRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentedParkings> rentedParkings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extensions> Extensions { get; set; }
    }
}
