//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalOffersForParking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentalOffersForParking()
        {
            this.daysAweekForOffers = new HashSet<daysAweekForOffer>();
        }
    
        public int offerCode { get; set; }
        public int parkingCode { get; set; }
        public System.DateTime startDateForOffer { get; set; }
        public Nullable<System.DateTime> endDateForOffer { get; set; }
        public System.TimeSpan startHourForOffer { get; set; }
        public Nullable<System.TimeSpan> endHourForOffer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daysAweekForOffer> daysAweekForOffers { get; set; }
        public virtual Parking Parking { get; set; }
    }
}
