//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentedParkings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rentedParkings()
        {
            this.Opinions = new HashSet<Opinions>();
        }
    
        public int rentedParkingCode { get; set; }
        public int offerCode { get; set; }
        public int requestCode { get; set; }
        public string dayOfWeekForOffer { get; set; }
        public string dayOfWeekForRequest { get; set; }
        public System.DateTime startDateForRequest { get; set; }
        public Nullable<System.DateTime> endDateForRequest { get; set; }
        public System.TimeSpan startHourForRequest { get; set; }
        public Nullable<System.TimeSpan> endHourForRequest { get; set; }
    
        public virtual daysAweekForOffer daysAweekForOffer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinions> Opinions { get; set; }
        public virtual parkingRentalRequests__ parkingRentalRequests__ { get; set; }
    }
}
