//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.parkingRentalRequests = new HashSet<parkingRentalRequest>();
        }
    
        public int carCode { get; set; }
        public string carNumber { get; set; }
        public Nullable<double> carLength { get; set; }
        public Nullable<double> carWidth { get; set; }
        public Nullable<double> carHeight { get; set; }
        public Nullable<double> carWeight { get; set; }
        public int userCode { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parkingRentalRequest> parkingRentalRequests { get; set; }
    }
}
