//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class daysAweekForOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public daysAweekForOffer()
        {
            this.rentedParkings = new HashSet<rentedParking>();
        }
    
        public int offerCode { get; set; }
        public int dayOfWeekForOffer { get; set; }
        public int DayId { get; set; }
    
        public virtual RentalOffersForParking RentalOffersForParking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentedParking> rentedParkings { get; set; }
    }
}
