//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkingRentalRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parkingRentalRequest()
        {
            this.daysAweekForRequests = new HashSet<daysAweekForRequest>();
            this.Extensions = new HashSet<Extension>();
        }
    
        public int requestCode { get; set; }
        public int carCode { get; set; }
        public System.DateTime startDateForRequest { get; set; }
        public Nullable<System.DateTime> endDateForRequest { get; set; }
        public System.TimeSpan startHourForRequest { get; set; }
        public Nullable<System.TimeSpan> endHourForRequest { get; set; }
        public string requestAdress { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daysAweekForRequest> daysAweekForRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extension> Extensions { get; set; }
    }
}
