//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentedParking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rentedParking()
        {
            this.Opinions = new HashSet<Opinion>();
        }
    
        public int rentedParkingCode { get; set; }
        public int offerCode { get; set; }
        public int requestCode { get; set; }
        public int dayOfWeekForOffer { get; set; }
        public int dayOfWeekForRequest { get; set; }
        public System.DateTime startDateForRequest { get; set; }
        public Nullable<System.DateTime> endDateForRequest { get; set; }
        public System.TimeSpan startHourForRequest { get; set; }
        public Nullable<System.TimeSpan> endHourForRequest { get; set; }
    
        public virtual daysAweekForRequest daysAweekForRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinions { get; set; }
        public virtual daysAweekForOffer daysAweekForOffer { get; set; }
    }
}
